### ISSUE TITLE
Testing - Unhealthy container alerting for DNS Cluster

### ISSUE THREAD

**Issue by babatundek** [ministryofjustice/nvvs-devops#494] opened 2023-10-23 09:59 UTC
This is the testing for [293](https://app.zenhub.com/workspaces/nvvs-devops-622a0b371800e400133bb924/issues/gh/ministryofjustice/staff-device-dns-dhcp-infrastructure/293)

User Story:

**As a DevOps Engineer**, I want to be able to have confidence in my services alerting capability. Currently the alerting is only configured on production environments. I want to extend this capability to both Development & Pre-Production, to allow me to test alerting changes, giving me the confidence in the change, without needing to test directly on production.

Ticket Outcomes:
 - Extend alerting to both: Development & Pre-Production
 - Test new alert from ticket, that was added in ticket: https://app.zenhub.com/workspaces/nvvs-devops-622a0b371800e400133bb924/issues/gh/ministryofjustice/staff-device-dns-dhcp-infrastructure/294

**Comment by jamesgreen-moj** [comment] 2023-10-26 11:43
Viewing the costs for the monitoring application on cost explorer, I can see the service is costing $300.37 on average. If we repeat the current setup across all environments we could see the costs raise to $900 per month.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0IxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5f16f54a8b59fceedf25cfc0523465578b369f9/Screenshot%202023-10-26%20at%2010.12.36.png)

**Comment by jamesgreen-moj** [comment] 2023-10-27 10:24
After a team discussion of this ticket, rather than moving this to shared services now. We are going to use the infrastructure currently deployed to production and extend that capability to other environments. (This will not cost anymore money) - @babatundek

**Comment by jamesgreen-moj** [comment] 2024-01-12 09:49
Deployment went out to production with changes to extending monitoring: https://github.com/ministryofjustice/nvvs-devops-monitor/actions/runs/7478550594

https://github.com/ministryofjustice/nvvs-devops-monitor/pull/235
https://github.com/ministryofjustice/nvvs-devops-monitor/pull/236
https://github.com/ministryofjustice/nvvs-devops-monitor/pull/237
https://github.com/ministryofjustice/nvvs-devops-monitor/pull/238

Unfortunately production monitoring has not been updated with the alerts that have been added as part of this change. And the service seems to be failing to display data from CloudWatch after this deployment has been made. Investigation into these two issues are on going.

**Comment by NNavickas1** [comment] 2024-01-22 10:36
moving out of the sprint to allow focus on CRL SPIKE

**Comment by jamesgreen-moj** [comment] 2024-02-08 10:00
We now how dev rasing alerts to slack: <img width="1160" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd00vQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c713c4a306ae2dcdc7d48954a88c2b8a2fba380/image.png" alt="image.png" />

**Comment by jamesgreen-moj** [comment] 2024-02-08 16:42
PR for pre-production: https://github.com/ministryofjustice/nvvs-devops-monitor/pull/254

**Comment by juddin927** [comment] 2024-02-09 11:52
This has been pushed to the production now. Dev and preproduction alerting for DNS/DHCP are live now.

**Closed** 2024-02-12 09:40 UTC
